### ISSUE TITLE
Optionally return non-zero if warnings or errors encountered

### ISSUE THREAD

**Issue by rgabbard** [shahraj81/aida#24]
If I remember from when I once wrote a NIST validator myself, NIST's setup wants `0` to be returned even on error. However, for users, especially those validating many submissions in parallel in an automated way, it would be useful if the user could request for a non-zero exit value to be returned if errors (or perhaps also warnings) are present.

**Comment by shahraj81** [comment]
Done. The change is applied as a hotfix on the latest release branch.

See commit:

- Validation script now return error code 255 if problems are encountered

**Comment by rgabbard** [comment]
@shahraj81 : Thanks for the quick fix!
